const BASE_URL = 'http://localhost:8080'
export const consts = {
	// API's
	IMG_URL: (filename) => `${BASE_URL}/uploads/${filename}`,
	GET_ALL_MASJIDS_API_PUBLIC: `${BASE_URL}/api/public/masjid`,
	GET_MASJID_BY_ID_PUBLIC: (slug) => `${BASE_URL}/api/public/masjid/masjid-by-slug/${slug}`,
	CREATE_CONTACT_API_PUBLIC: `${BASE_URL}/api/contact`,
	LOGIN_API_PUBLIC: `${BASE_URL}/api/login`,
	RESET_PASSWORD_API_PUBLIC: `${BASE_URL}/api/reset-password`,
	// Admin API's
	GET_BANNER_API: `${BASE_URL}/api/banner`,
	ADD_BANNER_API: `${BASE_URL}/api/banner/add`,
	GET_ALL_MASJID_API: `${BASE_URL}/api/masjid/`,
	GET_MASJID_BY_ID_API: (id) => `${BASE_URL}/api/masjid/${id}`,
	CREATE_MASJID_API: `${BASE_URL}/api/masjid/add`,
	DELETE_MASJID_API: (id) => `${BASE_URL}/api/masjid/${id}`,
	UPDATE_MASJID_API: (id) => `${BASE_URL}/api/masjid/${id}`,
	ADD_NAMAZ_TIME_API: `${BASE_URL}/api/namaz-time/add`,
	EDIT_NAMAZ_TIME_API: (id) => `${BASE_URL}/api/namaz-time/update/${id}`,
	GET_NAMAZ_TIMETABLE_API: (id) => `${BASE_URL}/api/namaz-time/${id}`,
	GET_ALL_USER_API: `${BASE_URL}/api/users`,
	ADD_USER_API: `${BASE_URL}/api/users/add`,
	GET_USER_API: (id) => `${BASE_URL}/api/users/get-user/${id}`,
	EDIT_USER_API: (id) => `${BASE_URL}/api/users/edit/${id}`,
	DELETE_USER_API: (id) => `${BASE_URL}/api/users/delete-user/${id}`,
	GET_ROLE_API: `${BASE_URL}/api/role`,
	GET_ALL_LOGS_API: `${BASE_URL}/api/logs`,
	GET_ALL_CONTACT_API: `${BASE_URL}/api/contact/get-all-contacts/`,
	GET_CONTACT_BY_ID_API: (id) => `${BASE_URL}/api/contact/get-all-contacts/${id}`,
	DELETE_CONTACT_API: (id) => `${BASE_URL}/api/contact/delete-contact/${id}`,
	GET_CSRF_TOKEN: (uniqueStr) => `${BASE_URL}/api/csrf-token/${uniqueStr}`,
	GET_ALL_DASHBOARD_API: `${BASE_URL}/api/dashboard`,
	VALIDATE_API: `${BASE_URL}/api/validate-token`,
	GET_USER_PROFILE_API: `${BASE_URL}/api/users/get-user-profile`,
	LOGOUT_API: `${BASE_URL}/api/logout`,
	RESET_PASSWORD_API: `${BASE_URL}/api/users/profile/reset-password`,
	FORGOT_PASSWORD_API_PUBLIC: `${BASE_URL}/api/forgot-password`,
}